import path from 'node:path';
import type { Diagnostic } from '../types/diagnostic.js';

export function generateMarkdownReport(diagnostics: Diagnostic[]): string {
  const errors = diagnostics.filter((d) => d.severity === 'error').length;
  const warnings = diagnostics.filter((d) => d.severity === 'warn').length;

  let md = `# 🛡️ Memory Leak Detection Report\n\n`;
  md += `**Summary:** 🔴 ${errors} Errors | 🟡 ${warnings} Warnings | ℹ️ ${diagnostics.length} Total\n\n`;

  if (diagnostics.length === 0) {
    md += `✅ **No memory leaks detected!** Excellent job keeping your application clean.\n`;
    return md;
  }

  md += `| Severity | Rule ID | File | Message |\n`;
  md += `| :---: | :--- | :--- | :--- |\n`;

  for (const d of diagnostics) {
    const icon = d.severity === 'error' ? '🔴' : '🟡';
    const relFile = path.relative(process.cwd(), d.file).replace(/\\/g, '/');

    // Sanitize message for markdown table
    const safeMsg = d.message.replace(/\|/g, '&#124;').replace(/\n/g, ' ');
    const safeSugg = d.suggestion ? `<br/><br/>*💡 Suggestion: ${d.suggestion.replace(/\|/g, '&#124;')}*` : '';

    md += `| ${icon} | \`${d.ruleId}\` | \`${relFile}:${d.line}\` | ${safeMsg}${safeSugg} |\n`;
  }

  md += `\n---\n*Generated by \`vite-plugin-memory-leak-detector\`*\n`;
  return md;
}
